make:
	/Users/benjamin/Downloads/scala-2.12.1/bin/scalac *.scala
dd:
	/Users/benjamin/Downloads/scala-2.12.1/bin/scalac Dungeon.scala Dragon.scala Knight.scala

ddr:
	../run.sh Dungeon

p4:
	/Users/benjamin/Downloads/scala-2.12.1/bin/scalac temperature.scala tmp_tester.scala

rp4:
	../run.sh Tester

clean:
	rm -rf value/  expression/ system/ temperature/ character/ *.class