make:
	/Users/benjamin/Downloads/scala-2.12.1/bin/scalac *.scala
dd:
	/Users/benjamin/Downloads/scala-2.12.1/bin/scalac Dungeon.scala Dragon.scala Knight.scala

ddr:
	../run.sh Dungeon

clean:
	rm -rf value/  expression/ system/ *.class