CC=~/Downloads/scala-2.12.1/bin/scalac
EXEC=~/Downloads/scala-2.12.1/bin/scala
make:
	$(CC) Calculator.scala
int:
	$(EXEC) Calculator.scala
run:
	$(EXEC) Calculator
start_scala:
	$(EXEC)
clean:
	rm *.class